version: '3.1'
services:
  Server:
    image: 'todo-backend'
    ports:
      - "8585:8585"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2611
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  Client:
    image: 'todo-frontend'
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - Server

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=2611
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5